server.ssl.enabled=false
server.port=${PORT:8080}

spring.data.mongodb.host=localhost
spring.elasticsearch.uris=http://localhost:9200
taymsozluk.security.enabled=true

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

taymsozluk.nextjs.revalidate-base-url=http://localhost:3000/api/revalidate
